<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/pubsub_api.proto

namespace Eventbus\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This feature is part of an open beta release and is subject to the applicable
 * Beta Services Terms provided at Agreements and Terms
 * (https://www.salesforce.com/company/legal/agreements/).
 * There is no guaranteed 1:1 CommitReplayRequest to CommitReplayResponse.
 * N CommitReplayRequest(s) can get compressed in a batch resulting in a single
 * CommitReplayResponse which reflects the latest values of last
 * CommitReplayRequest in that batch.
 *
 * Generated from protobuf message <code>eventbus.v1.CommitReplayResponse</code>
 */
class CommitReplayResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * commit_request_id to identify commit responses.
     *
     * Generated from protobuf field <code>string commit_request_id = 1;</code>
     */
    protected $commit_request_id = '';
    /**
     * replayId that may have been committed
     *
     * Generated from protobuf field <code>bytes replay_id = 2;</code>
     */
    protected $replay_id = '';
    /**
     * for failed commits
     *
     * Generated from protobuf field <code>.eventbus.v1.Error error = 3;</code>
     */
    protected $error = null;
    /**
     * time when server received request in epoch ms
     *
     * Generated from protobuf field <code>int64 process_time = 4;</code>
     */
    protected $process_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $commit_request_id
     *           commit_request_id to identify commit responses.
     *     @type string $replay_id
     *           replayId that may have been committed
     *     @type \Eventbus\V1\Error $error
     *           for failed commits
     *     @type int|string $process_time
     *           time when server received request in epoch ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtoFiles\PubsubApi::initOnce();
        parent::__construct($data);
    }

    /**
     * commit_request_id to identify commit responses.
     *
     * Generated from protobuf field <code>string commit_request_id = 1;</code>
     * @return string
     */
    public function getCommitRequestId()
    {
        return $this->commit_request_id;
    }

    /**
     * commit_request_id to identify commit responses.
     *
     * Generated from protobuf field <code>string commit_request_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCommitRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->commit_request_id = $var;

        return $this;
    }

    /**
     * replayId that may have been committed
     *
     * Generated from protobuf field <code>bytes replay_id = 2;</code>
     * @return string
     */
    public function getReplayId()
    {
        return $this->replay_id;
    }

    /**
     * replayId that may have been committed
     *
     * Generated from protobuf field <code>bytes replay_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReplayId($var)
    {
        GPBUtil::checkString($var, False);
        $this->replay_id = $var;

        return $this;
    }

    /**
     * for failed commits
     *
     * Generated from protobuf field <code>.eventbus.v1.Error error = 3;</code>
     * @return \Eventbus\V1\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * for failed commits
     *
     * Generated from protobuf field <code>.eventbus.v1.Error error = 3;</code>
     * @param \Eventbus\V1\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Eventbus\V1\Error::class);
        $this->error = $var;

        return $this;
    }

    /**
     * time when server received request in epoch ms
     *
     * Generated from protobuf field <code>int64 process_time = 4;</code>
     * @return int|string
     */
    public function getProcessTime()
    {
        return $this->process_time;
    }

    /**
     * time when server received request in epoch ms
     *
     * Generated from protobuf field <code>int64 process_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProcessTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->process_time = $var;

        return $this;
    }

}

