<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/pubsub_api.proto

namespace Eventbus\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Contains error information for an error that an RPC method returns.
 *
 * Generated from protobuf message <code>eventbus.v1.Error</code>
 */
class Error extends \Google\Protobuf\Internal\Message
{
    /**
     * Error code
     *
     * Generated from protobuf field <code>.eventbus.v1.ErrorCode code = 1;</code>
     */
    protected $code = 0;
    /**
     * Error message
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    protected $msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *           Error code
     *     @type string $msg
     *           Error message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtoFiles\PubsubApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Error code
     *
     * Generated from protobuf field <code>.eventbus.v1.ErrorCode code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Error code
     *
     * Generated from protobuf field <code>.eventbus.v1.ErrorCode code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkEnum($var, \Eventbus\V1\ErrorCode::class);
        $this->code = $var;

        return $this;
    }

    /**
     * Error message
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Error message
     *
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

}

