<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/pubsub_api.proto

namespace Eventbus\V1;

use UnexpectedValueException;

/**
 * Supported error codes
 *
 * Protobuf type <code>eventbus.v1.ErrorCode</code>
 */
class ErrorCode
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>PUBLISH = 1;</code>
     */
    const PUBLISH = 1;
    /**
     * ErrorCode for unrecoverable commit errors.
     *
     * Generated from protobuf enum <code>COMMIT = 2;</code>
     */
    const COMMIT = 2;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::PUBLISH => 'PUBLISH',
        self::COMMIT => 'COMMIT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

