<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/pubsub_api.proto

namespace Eventbus\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response for the Subscribe streaming RPC method. This returns ConsumerEvent(s).
 * If there are no events to deliver, the server sends an empty batch fetch response with the latest replay ID. The
 * empty fetch response is sent within 270 seconds. An empty fetch response provides a periodic keepalive from the
 * server and the latest replay ID.
 *
 * Generated from protobuf message <code>eventbus.v1.FetchResponse</code>
 */
class FetchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Received events for subscription for client consumption
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.ConsumerEvent events = 1;</code>
     */
    private $events;
    /**
     * Latest replay ID of a subscription. Enables clients with an updated replay value so that they can keep track
     * of their last consumed replay. Clients will not have to start a subscription at a very old replay in the case where a resubscribe is necessary.
     *
     * Generated from protobuf field <code>bytes latest_replay_id = 2;</code>
     */
    protected $latest_replay_id = '';
    /**
     * RPC ID used to trace errors.
     *
     * Generated from protobuf field <code>string rpc_id = 3;</code>
     */
    protected $rpc_id = '';
    /**
     * Number of remaining events to be delivered to the client for a Subscribe RPC call.
     *
     * Generated from protobuf field <code>int32 pending_num_requested = 4;</code>
     */
    protected $pending_num_requested = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Eventbus\V1\ConsumerEvent>|\Google\Protobuf\Internal\RepeatedField $events
     *           Received events for subscription for client consumption
     *     @type string $latest_replay_id
     *           Latest replay ID of a subscription. Enables clients with an updated replay value so that they can keep track
     *           of their last consumed replay. Clients will not have to start a subscription at a very old replay in the case where a resubscribe is necessary.
     *     @type string $rpc_id
     *           RPC ID used to trace errors.
     *     @type int $pending_num_requested
     *           Number of remaining events to be delivered to the client for a Subscribe RPC call.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtoFiles\PubsubApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Received events for subscription for client consumption
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.ConsumerEvent events = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Received events for subscription for client consumption
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.ConsumerEvent events = 1;</code>
     * @param array<\Eventbus\V1\ConsumerEvent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eventbus\V1\ConsumerEvent::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Latest replay ID of a subscription. Enables clients with an updated replay value so that they can keep track
     * of their last consumed replay. Clients will not have to start a subscription at a very old replay in the case where a resubscribe is necessary.
     *
     * Generated from protobuf field <code>bytes latest_replay_id = 2;</code>
     * @return string
     */
    public function getLatestReplayId()
    {
        return $this->latest_replay_id;
    }

    /**
     * Latest replay ID of a subscription. Enables clients with an updated replay value so that they can keep track
     * of their last consumed replay. Clients will not have to start a subscription at a very old replay in the case where a resubscribe is necessary.
     *
     * Generated from protobuf field <code>bytes latest_replay_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLatestReplayId($var)
    {
        GPBUtil::checkString($var, False);
        $this->latest_replay_id = $var;

        return $this;
    }

    /**
     * RPC ID used to trace errors.
     *
     * Generated from protobuf field <code>string rpc_id = 3;</code>
     * @return string
     */
    public function getRpcId()
    {
        return $this->rpc_id;
    }

    /**
     * RPC ID used to trace errors.
     *
     * Generated from protobuf field <code>string rpc_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRpcId($var)
    {
        GPBUtil::checkString($var, True);
        $this->rpc_id = $var;

        return $this;
    }

    /**
     * Number of remaining events to be delivered to the client for a Subscribe RPC call.
     *
     * Generated from protobuf field <code>int32 pending_num_requested = 4;</code>
     * @return int
     */
    public function getPendingNumRequested()
    {
        return $this->pending_num_requested;
    }

    /**
     * Number of remaining events to be delivered to the client for a Subscribe RPC call.
     *
     * Generated from protobuf field <code>int32 pending_num_requested = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPendingNumRequested($var)
    {
        GPBUtil::checkInt32($var);
        $this->pending_num_requested = $var;

        return $this;
    }

}

