<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/pubsub_api.proto

namespace Eventbus\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents an event that an event publishing app creates.
 *
 * Generated from protobuf message <code>eventbus.v1.ProducerEvent</code>
 */
class ProducerEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Either a user-provided ID or a system generated guid
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Schema fingerprint for this event which is hash of the schema
     *
     * Generated from protobuf field <code>string schema_id = 2;</code>
     */
    protected $schema_id = '';
    /**
     * The message data field
     *
     * Generated from protobuf field <code>bytes payload = 3;</code>
     */
    protected $payload = '';
    /**
     * Reserved for future use. Key-value pairs of headers.
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.EventHeader headers = 4;</code>
     */
    private $headers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Either a user-provided ID or a system generated guid
     *     @type string $schema_id
     *           Schema fingerprint for this event which is hash of the schema
     *     @type string $payload
     *           The message data field
     *     @type array<\Eventbus\V1\EventHeader>|\Google\Protobuf\Internal\RepeatedField $headers
     *           Reserved for future use. Key-value pairs of headers.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtoFiles\PubsubApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Either a user-provided ID or a system generated guid
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Either a user-provided ID or a system generated guid
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Schema fingerprint for this event which is hash of the schema
     *
     * Generated from protobuf field <code>string schema_id = 2;</code>
     * @return string
     */
    public function getSchemaId()
    {
        return $this->schema_id;
    }

    /**
     * Schema fingerprint for this event which is hash of the schema
     *
     * Generated from protobuf field <code>string schema_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaId($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema_id = $var;

        return $this;
    }

    /**
     * The message data field
     *
     * Generated from protobuf field <code>bytes payload = 3;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * The message data field
     *
     * Generated from protobuf field <code>bytes payload = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

    /**
     * Reserved for future use. Key-value pairs of headers.
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.EventHeader headers = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Reserved for future use. Key-value pairs of headers.
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.EventHeader headers = 4;</code>
     * @param array<\Eventbus\V1\EventHeader>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eventbus\V1\EventHeader::class);
        $this->headers = $arr;

        return $this;
    }

}

