<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/pubsub_api.proto

namespace Eventbus\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for the Publish and PublishStream RPC method.
 *
 * Generated from protobuf message <code>eventbus.v1.PublishRequest</code>
 */
class PublishRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Topic to publish on
     *
     * Generated from protobuf field <code>string topic_name = 1;</code>
     */
    protected $topic_name = '';
    /**
     * Batch of ProducerEvent(s) to send
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
     */
    private $events;
    /**
     * For internal Salesforce use only.
     *
     * Generated from protobuf field <code>string auth_refresh = 3;</code>
     */
    protected $auth_refresh = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic_name
     *           Topic to publish on
     *     @type array<\Eventbus\V1\ProducerEvent>|\Google\Protobuf\Internal\RepeatedField $events
     *           Batch of ProducerEvent(s) to send
     *     @type string $auth_refresh
     *           For internal Salesforce use only.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtoFiles\PubsubApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Topic to publish on
     *
     * Generated from protobuf field <code>string topic_name = 1;</code>
     * @return string
     */
    public function getTopicName()
    {
        return $this->topic_name;
    }

    /**
     * Topic to publish on
     *
     * Generated from protobuf field <code>string topic_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTopicName($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic_name = $var;

        return $this;
    }

    /**
     * Batch of ProducerEvent(s) to send
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Batch of ProducerEvent(s) to send
     *
     * Generated from protobuf field <code>repeated .eventbus.v1.ProducerEvent events = 2;</code>
     * @param array<\Eventbus\V1\ProducerEvent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eventbus\V1\ProducerEvent::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * For internal Salesforce use only.
     *
     * Generated from protobuf field <code>string auth_refresh = 3;</code>
     * @return string
     */
    public function getAuthRefresh()
    {
        return $this->auth_refresh;
    }

    /**
     * For internal Salesforce use only.
     *
     * Generated from protobuf field <code>string auth_refresh = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthRefresh($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth_refresh = $var;

        return $this;
    }

}

