<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/pubsub_api.proto

namespace Eventbus\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for the GetSchema RPC method. The schema request is based on the event schema ID.
 *
 * Generated from protobuf message <code>eventbus.v1.SchemaRequest</code>
 */
class SchemaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Schema fingerprint for this event, which is a hash of the schema.
     *
     * Generated from protobuf field <code>string schema_id = 1;</code>
     */
    protected $schema_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $schema_id
     *           Schema fingerprint for this event, which is a hash of the schema.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtoFiles\PubsubApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Schema fingerprint for this event, which is a hash of the schema.
     *
     * Generated from protobuf field <code>string schema_id = 1;</code>
     * @return string
     */
    public function getSchemaId()
    {
        return $this->schema_id;
    }

    /**
     * Schema fingerprint for this event, which is a hash of the schema.
     *
     * Generated from protobuf field <code>string schema_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaId($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema_id = $var;

        return $this;
    }

}

