<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/pubsub_api.proto

namespace Eventbus\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A request message for GetTopic. Note that the tenant/org is not directly referenced
 * in the request, but is implicitly identified by the authentication headers.
 *
 * Generated from protobuf message <code>eventbus.v1.TopicRequest</code>
 */
class TopicRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the topic to retrieve.
     *
     * Generated from protobuf field <code>string topic_name = 1;</code>
     */
    protected $topic_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $topic_name
     *           The name of the topic to retrieve.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProtoFiles\PubsubApi::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the topic to retrieve.
     *
     * Generated from protobuf field <code>string topic_name = 1;</code>
     * @return string
     */
    public function getTopicName()
    {
        return $this->topic_name;
    }

    /**
     * The name of the topic to retrieve.
     *
     * Generated from protobuf field <code>string topic_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTopicName($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic_name = $var;

        return $this;
    }

}

